# Generated by Django 4.2.4 on 2023-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_toppers_toppermarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppers',
            name='yearOfexam',
            field=models.IntegerField(),
        ),
    ]
