# Generated by Django 4.2.4 on 2023-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_toppers_yearofexam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppers',
            old_name='topperImage',
            new_name='topper1Image',
        ),
        migrations.RenameField(
            model_name='toppers',
            old_name='topperMarks',
            new_name='topper1Marks',
        ),
        migrations.RenameField(
            model_name='toppers',
            old_name='topperName',
            new_name='topper1Name',
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper2Image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper2Marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper2Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper3Image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper3Marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppers',
            name='topper3Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
