# Generated by Django 4.2.6 on 2023-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_pictures_picturedate_pictures_picturename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcementName', models.CharField(max_length=50)),
                ('announcement', models.CharField(max_length=200)),
            ],
        ),
    ]
