# Generated by Django 5.0.2 on 2024-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='toppers',
            name='topper1Image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='toppers',
            name='topper2Image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='toppers',
            name='topper3Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
