# Generated by Django 5.0.2 on 2024-03-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_testimonials_noofstars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='noOfStars',
        ),
    ]
